### ISSUE TITLE
Array of languages for countries with multiple

### ISSUE THREAD

**Issue by kbernou** [xaca/juego_banderas#44]
Should countries that have multiple languages use an array to store the languages, instead of just having one (or a comma separated list within a string, which I've seen in there as well)? 

This would make it easier to deal with multiple languages individually (assuming that's a requirement at all and/or in scope for this project).

**Comment by xaca** [comment]
@kbernou Yes, is better that way, because is easy to iterate over and array, for futter manipulations.  Could you update that?

**Comment by kbernou** [comment]
I'll get it done.
